### ISSUE TITLE
Natural Key not implemented?

### ISSUE THREAD

**Issue by zhao-li** [microsoft/mssql-django#45]
Thank you for creating this library so we can support MS SQL using Django.

I am trying to seed my Django app using natural keys instead of hard-coding IDs/PKs like this: https://docs.djangoproject.com/en/3.2/topics/serialization/#natural-keys

But I don't think this library (e.g. mssql-django) recognizes natural keys.

I've tried the same code/YAML that is working with a Django app using PostgreSQL on a Django using MS SQL.  But I have been unsuccessful getting the natural keys working on the MS SQL Django app.
Also, when I issue
`/manage.py dumpdata --natural-foreign --format yaml`
The output YAML file still has normal IDs.

Are natural keys supposed to be working and I did something wrong?
Or are natural keys not implemented and it might or might not be on the roadmap?

Thank you for your time 🙏🏻

**Comment by absci** [comment]
I'm not too familiar with natural keys. Could you provide some code samples that reproduce this issue?

**Comment by zhao-li** [comment]
@absci Thank you for following up with this request.

I'm not too familiar with natural keys either, but the following is what I gather.

If I define a `get_by_natural_key` method on the model manager (https://gitlab.com/porter4/backend/-/blob/master/trading_accounts/managers.py#L9-12),
then I can then refer to associated models in my seeds using natural names (https://gitlab.com/porter4/backend/-/blob/master/trading_accounts/seeds.yaml#L10)
instead of IDs, like this:
```
--- # basic farewell
- model: greetings.Greeting
  id: 1 # hardcode id until natural_keys work; it might be a mssql-django issue
  fields:
    message: hello, world
- model: farewells.Farewell
  fields:
    message: bye, world
    greeting: 1 # hardcode id until natural_keys work; it might be a
    # mssql-django issue
```

The only difference, that I can think of, between the 2 different sets of code is that one uses PostgreSQL and the other uses MS SQL via the `mssql-django` library.

Please let me know if there's more information I can share that can help resolve this issue.

Thank you again for your time 🙏🏻
